### ISSUE TITLE
Program exits if AndyADB is missing

### ISSUE THREAD

**Issue by Rhythm-of-Time** [BetaLeaf/AndyRoot#2]
Having rooted Andy with an older method before, AndyADB had been manually deleted. If AndyRoot.exe encounters this condition, ShellExecute on Line 77 exits the program with an error message and aborts the AutoIt script. Cool thing, anyway! You make it very easy to root Andyroid, and remind me to be using that powerful script language more often...

**Comment by AetherCollective** [comment]
Uninstall Andy Emulator and reinstall the latest version from the website. I cannot control what files other programs delete.

**Comment by Rhythm-of-Time** [comment]
AndyRootkitz ADBPatch removed it. Nevermind, your program is way better! 
I found AndyADB.exe in the tools directory of the Andy offline installer 
and copied it to the program directory instead of reinstalling. Maybe it 
would help to check for the presence of this file, too, and have the 
program spit out a hint to uninstall Andy (unless the user knows where 
the file is).

If (ProcessExists("AndyADB.exe") = 0) And (FileExists(""C:\Program 
Files\Andy\AndyADB.exe")) Then
     ShellExecute("AndyADB.exe", "", $workingdirectory)
     Sleep(5000)
Else
MsgBox(0, "Andy", "AndyADB.exe not found. Installation is corrupt. 
Please uninstall Andy and then rerun this app.")
exit
EndIf

Thank you for the nice scipt!

Cheers,

Christoph Schätzle

**Comment by AetherCollective** [comment]
No problem.
