### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by juicecup** [BetaLeaf/AndyRoot#6]
idk if you will respond but i really hope your do, when i ran the program it opened andy but root checker and superuser werent installed so i installed them and it wasnt rooted please help

**Comment by AetherCollective** [comment]
Hey thanks for letting me know. I cannot reproduce this on my end. This is a commonly reported issue. Try rerunning the script after rebooting your computer and/or uninstalling AndyRoot.

**Comment by AetherCollective** [comment]
Could not reproduce. If you still have issues, please download the latest version of AndyEmulator and AndyRoot, then try again.
